redis:
  local:
    ip: 127.0.0.1
    port: 6379
    pool_size: 100
    max_conn: 100
    conn_timeout: 1000
    read_timeout: 1000
    write_timeout: 100

postgres:
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  dbname: "q1"
  sslmode: disable
  timezone: Asia/Taipei
  max-open-conns: 25
  max-idle-conns: 10
  conn-max-lifetime: 1h

server-addr: :8080

security:
  jwt-secret: 123456
  jwt-expire-time: 15m
