redis:
  local:
    ip: 127.0.0.1
    port: 6379
    pool_size: 100
    max_conn: 100
    conn_timeout: 1000
    read_timeout: 1000
    write_timeout: 100

posgres:
  user: postgres
  password: postgres
  host: localhost
  port: 5432
  dbname: "q1"

server-addr: localhost:8080